site_name: Beancount Importer Rules

watch:
  - docs/
  - mkdocs.yml
  - beancount_importer_rules/

theme:
  name: "material"

  custom_dir: docs/overrides

  font:
    code: Roboto Mono
    text: Roboto Slab

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline

        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

plugins:
  - search
  - tags
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
