# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.11
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Run test
          command: uv run python -m pytest ./tests -svvvv
  build-and-publish:
    docker:
      - image: cimg/python:3.10.11
    steps:
      - checkout
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Build
          command: uv build
      - run:
          name: Publish
          command: uv publish

workflows:
  test:
    jobs:
      - test:
          filters:
            # needed for deploy build
            # ref: https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681/7
            tags:
              only: /^.*/
      - build-and-publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
