site_name: BeanHub Import
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.svg
  palette:
    primary: deep purple
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.prune
    - navigation.footer
  custom_dir: overrides
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - 'BeanHub Import': 'index.md'
  - 'Import Scheme':
    - 'Root - Import Doc': 'scheme/import-doc.md'
    - 'Context': 'scheme/context.md'
    - 'Input Config': 'scheme/input-config.md'
    - 'Import Config':
      - 'Import Config': 'scheme/import-config/import-config.md'
      - 'Basic Match': 'scheme/import-config/basic-match.md'
      - 'Match with variables': 'scheme/import-config/match-with-vars.md'
      - 'Omit': 'scheme/import-config/omit.md'
copyright: Copyright &copy; 2024 Launch Platform LLC
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/launchplatform
    - icon: fontawesome/solid/house
      link: https://beanhub.io
  generator: false
  analytics:
    provider: custom
